/*
 * Author: Thomas, Lindley
 * Date: 06/16/2020
 * Program: Project2.java - Gui and methods to calcualte different discounts of vehicles and store information
 * into an arrray of objects that prints to console last five vehicles entered.
 */
package Project2;

import javax.swing.JOptionPane;

/**
 *
 * @author Thoma
 */
public class Project2 extends javax.swing.JFrame {

    /**
     * Creates new form Project2
     */
    public Project2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfMakeModel = new javax.swing.JTextField();
        tfSalesPrice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnHybrid = new javax.swing.JRadioButton();
        btnElectric = new javax.swing.JRadioButton();
        btnOther = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfMPG = new javax.swing.JTextField();
        tfWeight = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnComputeSalesTax = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        tfSalesTaxOut = new javax.swing.JTextField();
        btnDisplayReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automobile Sales Tax Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(1, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jLabel1.setText("Make and Model");

        jLabel2.setText("Sales Price");

        tfSalesPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalesPriceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMakeModel)
                    .addComponent(tfSalesPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMakeModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Automobile Type"));

        btnHybrid.setText("Hybrid");
        btnHybrid.setToolTipText("");
        btnHybrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHybridActionPerformed(evt);
            }
        });

        btnElectric.setText("Electric");
        btnElectric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElectricActionPerformed(evt);
            }
        });

        btnOther.setText("Other");
        btnOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherActionPerformed(evt);
            }
        });

        jLabel3.setText("Miles per Gallon");

        jLabel4.setText("Weight in Pounds");

        tfMPG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMPGKeyTyped(evt);
            }
        });

        tfWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfWeightKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnOther)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHybrid)
                    .addComponent(btnElectric))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMPG, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(tfWeight)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHybrid)
                    .addComponent(jLabel3)
                    .addComponent(tfMPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElectric)
                    .addComponent(jLabel4)
                    .addComponent(tfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOther)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnComputeSalesTax.setText("Compute Sales Tax");
        btnComputeSalesTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeSalesTaxActionPerformed(evt);
            }
        });

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        tfSalesTaxOut.setEditable(false);
        tfSalesTaxOut.setBackground(new java.awt.Color(204, 204, 204));
        tfSalesTaxOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalesTaxOutActionPerformed(evt);
            }
        });

        btnDisplayReport.setText("Display Report");
        btnDisplayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComputeSalesTax, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDisplayReport, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(tfSalesTaxOut, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComputeSalesTax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSalesTaxOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClearFields, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnDisplayReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //sets selection to an int so program can differentiate between hybrid, electric and normal cars
    private void btnElectricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElectricActionPerformed
        //must clear other selections
         if (selection == 0 || selection == 2){
        btnHybrid.setSelected(false);
        btnOther.setSelected(false);
        tfMPG.setText("");
        tfSalesTaxOut.setText("");
        }
        tfWeight.setEditable(true);
        tfMPG.setEditable(false);
        selection = 1;
    }//GEN-LAST:event_btnElectricActionPerformed
    //sets selection to an int so program can differentiate between hybrid, electric and normal cars
    private void btnHybridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHybridActionPerformed
        //must clear other selections
         if (selection == 0 || selection == 1){
        btnElectric.setSelected(false);
        btnOther.setSelected(false);
        tfWeight.setText("");
        tfSalesTaxOut.setText("");
        }
        tfMPG.setEditable(true);
        tfWeight.setEditable(false);
        selection = 2;
    }//GEN-LAST:event_btnHybridActionPerformed
    //sets selection to an int so program can differentiate between hybrid, electric and normal cars
    private void btnOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherActionPerformed
        //must clear other selections
        if (selection == 1 || selection == 2){
        btnElectric.setSelected(false);
        btnHybrid.setSelected(false);
        tfWeight.setText("");
        tfMPG.setText("");
        tfSalesTaxOut.setText("");
        }
        tfMPG.setEditable(false);
        tfWeight.setEditable(false);
        selection = 0;
    }//GEN-LAST:event_btnOtherActionPerformed
    //Clears all fields
    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        tfMPG.setText("");
        tfMakeModel.setText("");
        tfWeight.setText("");
        tfSalesTaxOut.setText("");
        tfSalesPrice.setText("");
        btnElectric.setSelected(false);
        btnHybrid.setSelected(false);
        btnOther.setSelected(false);
    }//GEN-LAST:event_btnClearFieldsActionPerformed
    //Makes sales tax text field not editable
    private void tfSalesTaxOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalesTaxOutActionPerformed
        tfSalesTaxOut.setEditable(false);
    }//GEN-LAST:event_tfSalesTaxOutActionPerformed
    //Creates Automobile objects
    private void btnComputeSalesTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeSalesTaxActionPerformed
        //Setting shared variables to what user enters in text fields makeModel and SalesPrice
        String makeModel = tfMakeModel.getText();
        int salesPrice = Integer.parseInt(tfSalesPrice.getText());
        //Creates different automobiles based on selection 
        if (selection == 0) {
            //n%5 allows user to continue adding to the array by dropping the remainder of the array index divided by 5
            //drops oldest object in array
            Automobile[n%5] = new Automobile(makeModel, salesPrice);
        } else if (selection == 1) {
            int weight = Integer.parseInt(tfWeight.getText());
            Automobile[n%5] = new Electric(makeModel, salesPrice, weight);
        } else if (selection == 2) {
            int mpg = Integer.parseInt(tfMPG.getText());
            Automobile[n%5] = new Hybrid(makeModel, salesPrice, mpg);
        }
        //prints salestax of current object
        double salesTaxOut = Automobile[n%5].salesTax();
        tfSalesTaxOut.setText(Double.toString(salesTaxOut));
        //increments array index
        n++;
    }//GEN-LAST:event_btnComputeSalesTaxActionPerformed
    //prints list of last 5 objects created
    private void btnDisplayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayReportActionPerformed
        //since first element of array is dropped and newest element added to the end of the array, it needs to print
        //from n%5 to the end of the array, then print the elements in the array before this point, which is done in the
        //second for loop.
        if(n>5){
            for (int i = n%5; i < 5; i++) {
                System.out.println(Automobile[i].toString());
            }
            for (int i = 0; i < n%5; i++){
                System.out.println(Automobile[i].toString());
            }
        }else{
            //need seperate loop if array of objects does not reach more than 5 elements
            for (int i = 0; i < n; i++){
            System.out.println(Automobile[i].toString());
            }
        }
    }//GEN-LAST:event_btnDisplayReportActionPerformed

    private void tfSalesPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalesPriceKeyTyped
        //allows users to only integers into the text fields by setting the accepted chars to 0 through 9
        //also has the unicode for backspace. Without backspace here, popup will display every backspace.
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '\u0008') {
            //allows text entry if numbers
            tfSalesPrice.setEditable(true);
        } else {
            //anything besides numbers and backspace will trigger a popupwindow
            tfSalesPrice.setEditable(false);
            tfSalesPrice.setText("");
            JOptionPane.showMessageDialog(null, "Enter Numbers only please", "Sales Price: ", JOptionPane.ERROR_MESSAGE);
            tfSalesPrice.setEditable(true);
        }
    }//GEN-LAST:event_tfSalesPriceKeyTyped

    private void tfMPGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMPGKeyTyped
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '\u0008') {
            tfMPG.setEditable(true);
        } else {
            tfMPG.setEditable(false);
            tfMPG.setText("");
            JOptionPane.showMessageDialog(null, "Enter Numbers only please", "MPG: ", JOptionPane.ERROR_MESSAGE);
            tfMPG.setEditable(true);
        }
    }//GEN-LAST:event_tfMPGKeyTyped

    private void tfWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfWeightKeyTyped
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '\u0008') {
            tfMPG.setEditable(true);
        } else {
            tfWeight.setEditable(false);
            tfWeight.setText("");
            JOptionPane.showMessageDialog(null, "Enter Numbers only please", "Weight Error ", JOptionPane.ERROR_MESSAGE);
            tfWeight.setEditable(true);
        }
    }//GEN-LAST:event_tfWeightKeyTyped
    // variables used throughout above, placed here to not get lost with gui code
    private int selection;
    private Automobile Automobile[] = new Automobile[5];
    private int n = 0;
    //allows the showing of the gui
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnComputeSalesTax;
    private javax.swing.JButton btnDisplayReport;
    private javax.swing.JRadioButton btnElectric;
    private javax.swing.JRadioButton btnHybrid;
    private javax.swing.JRadioButton btnOther;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfMPG;
    private javax.swing.JTextField tfMakeModel;
    private javax.swing.JTextField tfSalesPrice;
    private javax.swing.JTextField tfSalesTaxOut;
    private javax.swing.JTextField tfWeight;
    // End of variables declaration//GEN-END:variables
}
